CREATE TABLE JUGUETE (
	JUGUETE_ID SMALLSERIAL,
	JUGUETE_NOMBRE VARCHAR(30),
	JUGUETE_PRECIO NUMERIC(4, 2),
	JUGUETE_COSTE NUMERIC (4, 2),
	CONSTRAINT PK_JUGUETE PRIMARY KEY (JUGUETE_ID)
);
CREATE TABLE EMPRESA(
	EMPRESA_ID SMALLSERIAL,
	EMPRESA_NOMBRE VARCHAR(20),
	EMPRESA_CIF VARCHAR(20),
	EMPRESA_DIRECCIONPOSTAL VARCHAR(50),
	EMPRESA_DIRECCIONWEB VARCHAR(100),
	EMPRESA_TELEFONO VARCHAR(20),
	CONSTRAINT PK_EMPRESA PRIMARY KEY (EMPRESA_ID)
);
CREATE TABLE PARTICULAR(
	PARTICULAR_ID SMALLSERIAL,
	PARTICULAR_NOMBRE VARCHAR(20),
	PARTICULAR_APELLIDO VARCHAR(30),
	PARTICULAR_TELEFONO VARCHAR(20),
	PARTICULAR_DIRECCION VARCHAR(15),
	PARTICULAR_FIRMA VARCHAR(100),
	CONSTRAINT PK_PARTICULAR PRIMARY KEY (PARTICULAR_ID)
);
CREATE TABLE EMPRESAJUGUETE(
	EMPRESAJUGUETE_ID SMALLSERIAL,
	EMPRESAJUGUETE_EMPRESAID SMALLSERIAL NOT NULL,
	EMPRESAJUGUETE_JUGUETE SMALLSERIAL NOT NULL,
	EMPRESAJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_EMPRESAJUGUETE PRIMARY KEY (EMPRESAJUGUETE_ID),
	CONSTRAINT FK_EMPRESAJUGUETE_EMPRESAID FOREIGN KEY (EMPRESAJUGUETE_EMPRESAID) REFERENCES EMPRESA(EMPRESA_ID),
	CONSTRAINT FK_EMPRESAJUGUETE_JUGUETEID FOREIGN KEY (EMPRESAJUGUETE_JUGUETE) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_EMPRESAJUGUETE UNIQUE(EMPRESAJUGUETE_EMPRESAID, EMPRESAJUGUETE_JUGUETE)
);
CREATE TABLE PARTICULARJUGUETE(
	PARTICULARJUGUETE_ID SMALLSERIAL,
	PARTICULARJUGUETE_PARTICULARID SMALLSERIAL NOT NULL,
	PARTICULARJUGUETE_JUGUETEID SMALLSERIAL NOT NULL,
	PARTICULARJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PARTICULARJUGUETE PRIMARY KEY (PARTICULARJUGUETE_ID),
	CONSTRAINT FK_PARTICULARJUGUETE_PARTICULARID FOREIGN KEY (PARTICULARJUGUETE_PARTICULARID) REFERENCES PARTICULAR(PARTICULAR_ID),
	CONSTRAINT FK_PARTICULARJUGUETE_JUGUETEID FOREIGN KEY (PARTICULARJUGUETE_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_PARTICULARJUGUETE UNIQUE (
		PARTICULARJUGUETE_PARTICULARID,
		PARTICULARJUGUETE_JUGUETEID
	)
);
CREATE TABLE PEDIDOEMPRESA(
	PEDIDOEMPRESA_ID SMALLSERIAL,
	PEDIDOEMPRESA_EMPRESAID SMALLSERIAL NOT NULL,
	PEDIDOEMPRESA_FECHA DATE,
	PEDIDOEMPRESA_DIRECCIONENVIO VARCHAR(50),
	CONSTRAINT PK_PEDIDOEMPRESA PRIMARY KEY (PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESA_EMPRESAID FOREIGN KEY (PEDIDOEMPRESA_EMPRESAID) REFERENCES EMPRESA(EMPRESA_ID)
);
CREATE TABLE PEDIDOPARTICULAR (
	PEDIDOPARTICULAR_ID SMALLSERIAL,
	PEDIDOPARTICULAR_PARTICULARID SMALLSERIAL NOT NULL,
	PEDIDOPARTICULAR_FECHA DATE,
	CONSTRAINT PK_PEDIDOPARTICULAR PRIMARY KEY (PEDIDOPARTICULAR_ID),
	CONSTRAINT FK_PEDIDOPARTICULAR_PARTICULARID FOREIGN KEY (PEDIDOPARTICULAR_PARTICULARID) REFERENCES PARTICULAR(PARTICULAR_ID)
);
CREATE TABLE PEDIDOEMPRESAJUGUETE(
	PEDIDOEMPRESAJUGUETE_ID SMALLSERIAL,
	PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID SMALLSERIAL NOT NULL,
	PEDIDOEMPRESAJUGUETE_JUGUETEID SMALLSERIAL NOT NULL,
	PEDIDOEMPRESAJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PEDIDOEMPRESAJUGUETE PRIMARY KEY (PEDIDOEMPRESAJUGUETE_ID),
	CONSTRAINT FK_PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID FOREIGN KEY (PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID) REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESAJUGUETE_JUGUETEID FOREIGN KEY (PEDIDOEMPRESAJUGUETE_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_PEDIDOEMPRESAJUGUETE UNIQUE (
		PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID,
		PEDIDOEMPRESAJUGUETE_JUGUETEID
	)
);
CREATE TABLE PEDIDOEMPRESAPARTICULAR(
	PEDIDOEMPRESAPARTICULAR_ID SMALLSERIAL,
	PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID SMALLSERIAL NOT NULL,
	PEDIODEMPRESAPARTICULAR_PARTICULAR_ID SMALLSERIAL NOT NULL,
	PEDIDOEMPRESAPARTICULAR_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PEDIDOEMPRESAPARTICULAR PRIMARY KEY (PEDIDOEMPRESAPARTICULAR_ID),
	CONSTRAINT FK_PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESAID FOREIGN KEY (PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID) REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESAPARTICULAR_PARTICULARID FOREIGN KEY (PEDIODEMPRESAPARTICULAR_PARTICULAR_ID) REFERENCES PARTICULAR(PARTICULAR_ID),
	CONSTRAINT UQ_PEDIDOEMPRESAPARTICULAR UNIQUE (
		PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID,
		PEDIODEMPRESAPARTICULAR_PARTICULAR_ID
	)
);
CREATE TABLE ALBARAN(
	ALBARAN_ID SMALLSERIAL,
	ALBARAN_PEDIDOID SMALLSERIAL,
	ALBARAN_FECHA DATE,
	CONSTRAINT PK_ALBARAN PRIMARY KEY (ALBARAN_ID),
	CONSTRAINT FK_ALBARANPEDIDOID FOREIGN KEY (ALBARAN_PEDIDOID) REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID)
);
CREATE TABLE ALBARANJUGUETE(
	ALBARANJUGUETE_ID SMALLSERIAL,
	ALBARANJUGUETE_ALBARAN_ID SMALLSERIAL NOT NULL,
	ALBARANJUGUETE_JUGUETE_ID SMALLSERIAL NOT NULL,
	ALBARANJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_ALBARANJUGUETE PRIMARY KEY (ALBARANJUGUETE_ID),
	CONSTRAINT FK_ALBARANJUGUETE_ALBARANID FOREIGN KEY (ALBARANJUGUETE_ALBARAN_ID) REFERENCES ALBARAN(ALBARAN_ID),
	CONSTRAINT FK_ALBARANJUGUETE_JUGUETEID FOREIGN KEY (ALBARANJUGUETE_JUGUETE_ID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_ALBARANJUGUETE UNIQUE (
		ALBARANJUGUETE_ALBARAN_ID,
		ALBARANJUGUETE_JUGUETE_ID
	)
);
CREATE TABLE CLIENTE(
	CLIENTE_ID SMALLSERIAL,
	CLIENTE_NOMBRE VARCHAR NOT NULL,
	CLIENTE_APELLIDO VARCHAR,
	CLIENTE_TELEFONO NUMERIC,
	CLIENTE_EMAIL VARCHAR NOT NULL,
	CLIENTE_CIF VARCHAR,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_ID)
);
CREATE TABLE CARRITO(
	CARRITO_ID SMALLSERIAL,
	CARRITO_JUGUETEID SMALLSERIAL NOT NULL,
	CARRITO_CLIENTEID SMALLSERIAL NOT NULL,
	CARRITO_CANTIDAD NUMERIC,
	CONSTRAINT PK_CARRITO PRIMARY KEY (CARRITO_ID),
	CONSTRAINT FK_CARRITO_JUGUETEID FOREIGN KEY (CARRITO_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT FK_CARRITO_CLIENTEID FOREIGN KEY (CARRITO_CLIENTEID) REFERENCES CLIENTE(CLIENTE_ID),
	CONSTRAINT UQ_CARRITO UNIQUE (CARRITO_JUGUETEID, CARRITO_CLIENTEID)
);
CREATE TABLE DIRECCIONFACTURACION (
	DIRECCIONFACTURACION_ID SMALLSERIAL,
	DIRECCIONFACTURACION_CLIENTEID SMALLSERIAL,
	DIRECCIONFACTURACION_NOMBRE VARCHAR,
	CONSTRAINT PK_DIRECCIONFACTURACION PRIMARY KEY (DIRECCIONFACTURACION_ID),
	CONSTRAINT FK_DIRECCIONFACTURACION FOREIGN KEY (DIRECCIONFACTURACION_CLIENTEID) REFERENCES CLIENTE(CLIENTE_ID)
);
CREATE TABLE DIRECCIONENVIO (
	DIRECCIONENVIO_ID SMALLSERIAL,
	DIRECCIONENVIO_CLIENTEID SMALLSERIAL,
	DIRECCIONENVIO_NOMBRE VARCHAR,
	CONSTRAINT PK_DIRECCIONENVIO PRIMARY KEY (DIRECCIONENVIO_ID),
	CONSTRAINT FK_DIRECCIONENVIO FOREIGN KEY (DIRECCIONENVIO_CLIENTEID) REFERENCES CLIENTE(CLIENTE_ID)
);
CREATE TABLE PEDIDOCLIENTE(
	PEDIDOCLIENTE_ID SMALLSERIAL,
	PEDIDOCLIENTE_CLIENTE_ID SMALLSERIAL NOT NULL,
	PEDIDOCLIENTE_MPAGO VARCHAR,
	PEDIDOCLIENTE_FECHA DATE,
	CONSTRAINT PK_PEDIDOCLIENTE PRIMARY KEY (PEDIDOCLIENTE_ID),
	CONSTRAINT FK_PEDIDOCLIENTE FOREIGN KEY (PEDIDOCLIENTE_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
);
CREATE TABLE LINEAPEDIDO(
	LINEAPEDIDO_ID SMALLSERIAL,
	LINEAPEDIDO_JUGUETEID SMALLSERIAL NOT NULL,
	LINEAPEDIDO_PEDIDOID SMALLSERIAL NOT NULL,
	LINEAPEDIDO_CANTIDAD NUMERIC,
	CONSTRAINT PK_LINEAPEDIDO PRIMARY KEY (LINEAPEDIDO_ID),
	CONSTRAINT FK_LINEAPEDIDO_JUGUETEID FOREIGN KEY (LINEAPEDIDO_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT FK_LINEAPEDIDO_PEDIDOID FOREIGN KEY (LINEAPEDIDO_PEDIDOID) REFERENCES PEDIDOCLIENTE(PEDIDOCLIENTE_ID),
	CONSTRAINT UQ_LINEAPEDIDO UNIQUE (LINEAPEDIDO_JUGUETEID, LINEAPEDIDO_PEDIDOID)
);
CREATE TABLE CLIENTEALBARAN(
	CLIENTEALBARAN_ID SMALLSERIAL,
	CLIENTALBARAN_FACTURAID SMALLSERIAL,
	CLIENTEALBARAN_PEDIDOID SMALLSERIAL NOT NULL,
	CLIENTEALBARAN_FECHA DATE,
	CLIENTEALBARAN_ACEPTADO BOOLEAN,
	CONSTRAINT PK_CLIENTEALBARAN PRIMARY KEY (CLIENTEALBARAN_ID),
	CONSTRAINT FK_CLIENTEALBARAN FOREIGN KEY (CLIENTALBARAN_FACTURAID) REFERENCES CLIENTEFACTURA(CLIENTEFACTURA_ID)
);
CREATE TABLE LINEAALBARAN(
	LINEAALBARAN_ID SMALLSERIAL,
	LINEAALBARAN_JUGUETEID SMALLSERIAL NOT NULL,
	LINEAALBARAN_ALBARANID SMALLSERIAL NOT NULL,
	LINEAALBARAN_CANTIDAD NUMERIC,
	CONSTRAINT PK_LINEAALBARAN PRIMARY KEY (LINEAALBARAN_ID),
	CONSTRAINT FK_LINEAALBARAN_JUGUETEID FOREIGN KEY (LINEAALBARAN_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT FK_LINEAALBARAN_ALBARANID FOREIGN KEY (LINEAALBARAN_ALBARANID) REFERENCES CLIENTEALBARAN(CLIENTEALBARAN_ID),
	CONSTRAINT UQ_LINEAALBARAN UNIQUE (LINEAALBARAN_JUGUETEID, LINEAALBARAN_ALBARANID)
);
CREATE TABLE CLIENTEFACTURA(
	CLIENTEFACTURA_ID SMALLSERIAL,
	CLIENTEFACTURA_FECHA DATE,
	CLIENTEFACUTURA_ACEPTADO BOOLEAN,
	CONSTRAINT PK_CLIENTEFACTURA_ID PRIMARY KEY (CLIENTEFACTURA_ID)
);
CREATE TABLE TICKET(
	TICKET_ID SMALLSERIAL,
	TICKET_TIPOCOMPRA NUMERIC(3),
	TICKET_TIPOTARJETA NUMERIC(3),
	TICKET_TITULAR VARCHAR(30),
	TICKET_NUMERO VARCHAR(15),
	TICKET_DEVOLUCION DATE,
	CONSTRAINT PK_TICKET PRIMARY KEY (TICKET_ID)
);
CREATE TABLE JUGUETETICKET(
	JUGUETETICKET_ID SMALLSERIAL,
	JUGUETETICKET_JUGUETEID SMALLSERIAL NOT NULL,
	JUGUETETICKET_TICKETID SMALLSERIAL NOT NULL,
	JUGUETETICKET_CANTIDAD VARCHAR(3),
	CONSTRAINT PK_JUGUETETICKET PRIMARY KEY (JUGUETETICKET_ID),
	CONSTRAINT FK_JUGUETETICKET_JUGUETEID FOREIGN KEY (JUGUETETICKET_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT FK_JUGUETETICKET_TICKETID FOREIGN KEY (JUGUETETICKET_TICKETID) REFERENCES TICKET(TICKET_ID),
	CONSTRAINT UQ_JUGUETETICKET UNIQUE (JUGUETETICKET_JUGUETEID, JUGUETETICKET_TICKETID)
);
