CREATE TABLE JUGUETE (
	JUGUETE_ID SMALLSERIAL,
	JUGUETE_NOMBRE VARCHAR(30),
	JUGUETE_PRECIO NUMERIC(4,2),
	CONSTRAINT PK_JUGUETE PRIMARY KEY (JUGUETE_ID)
);
CREATE TABLE EMPRESA(
	EMPRESA_ID SMALLSERIAL,
	EMPRESA_NOMBRE VARCHAR(20),
	EMPRESA_CIF VARCHAR(20),
	EMPRESA_DIRECCIONPOSTAL VARCHAR(50),
	EMPRESA_DIRECCIONWEB VARCHAR(100),
	EMPRESA_TELEFONO VARCHAR(20),
	CONSTRAINT PK_EMPRESA PRIMARY KEY (EMPRESA_ID)
);
CREATE TABLE PARTICULAR(
	PARTICULAR_ID SMALLSERIAL,
	PARTICULAR_NOMBRE VARCHAR(20),
	PARTICULAR_APELLIDO VARCHAR(30),
	PARTICULAR_TELEFONO VARCHAR(20),
	PARTICULAR_DIRECCION VARCHAR(15),
	CONSTRAINT PK_PARTICULAR PRIMARY KEY (PARTICULAR_ID)
);
CREATE TABLE EMPRESAJUGUETE(
	EMPRESAJUGUETE_ID SMALLSERIAL,
	EMPRESAJUGUETE_EMPRESAID SMALLSERIAL,
	EMPRESAJUGUETE_JUGUETE SMALLSERIAL,
	EMPRESAJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_EMPRESAJUGUETE PRIMARY KEY (EMPRESAJUGUETE_ID),
	CONSTRAINT FK_EMPRESAJUGUETE_EMPRESAID
	FOREIGN KEY (EMPRESAJUGUETE_EMPRESAID)
	REFERENCES EMPRESA(EMPRESA_ID),
	CONSTRAINT FK_EMPRESAJUGUETE_JUGUETEID 
	FOREIGN KEY (EMPRESAJUGUETE_JUGUETE)
	REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_EMPRESAJUGUETE UNIQUE(EMPRESAJUGUETE_EMPRESAID, EMPRESAJUGUETE_JUGUETE)
);
CREATE TABLE PARTICULARJUGUETE(
	PARTICULARJUGUETE_ID SMALLSERIAL,
	PARTICULARJUGUETE_PARTICULARID SMALLSERIAL,
	PARTICULARJUGUETE_JUGUETEID SMALLSERIAL,
	PARTICULARJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PARTICULARJUGUETE PRIMARY KEY (PARTICULARJUGUETE_ID),
	CONSTRAINT FK_PARTICULARJUGUETE_PARTICULARID 
	FOREIGN KEY (PARTICULARJUGUETE_PARTICULARID)
	REFERENCES PARTICULAR(PARTICULAR_ID),
	CONSTRAINT FK_PARTICULARJUGUETE_JUGUETEID 
	FOREIGN KEY (PARTICULARJUGUETE_JUGUETEID)
	REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_PARTICULARJUGUETE UNIQUE (PARTICULARJUGUETE_PARTICULARID, PARTICULARJUGUETE_JUGUETEID)
);
CREATE TABLE PEDIDOEMPRESA(
	PEDIDOEMPRESA_ID SMALLSERIAL,
	PEDIDOEMPRESA_EMPRESAID SMALLSERIAL,
	PEDIDOEMPRESA_NOMBRE VARCHAR(30),
	PEDIDOEMPRESA_FECHA DATE,
	PEDIDOEMPRESA_DIRECCIONENVIO VARCHAR(50),
	CONSTRAINT PK_PEDIDOEMPRESA PRIMARY KEY (PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESA_EMPRESAID 
	FOREIGN KEY (PEDIDOEMPRESA_EMPRESAID) 
	REFERENCES EMPRESA(EMPRESA_ID)
);
CREATE TABLE PEDIDOPARTICULAR (
	PEDIDOPARTICULAR_ID SMALLSERIAL,
	PEDIDOPARTICULAR_PARTICULARID SMALLSERIAL,
	PEDIDOPARTICULAR_FECHA DATE,
	CONSTRAINT PK_PEDIDOPARTICULAR PRIMARY KEY (PEDIDOPARTICULAR_ID),
	CONSTRAINT FK_PEDIDOPARTICULAR_PARTICULARID 
	FOREIGN KEY (PEDIDOPARTICULAR_PARTICULARID)
	REFERENCES PARTICULAR(PARTICULAR_ID)
);
CREATE TABLE PEDIDOEMPRESAJUGUETE(
	PEDIDOEMPRESAJUGUETE_ID SMALLSERIAL,
	PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID SMALLSERIAL,
	PEDIDOEMPRESAJUGUETE_JUGUETEID SMALLSERIAL,
	PEDIDOEMPRESAJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PEDIDOEMPRESAJUGUETE PRIMARY KEY (PEDIDOEMPRESAJUGUETE_ID),
	CONSTRAINT FK_PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID 
	FOREIGN KEY (PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID)
	REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESAJUGUETE_JUGUETEID 
	FOREIGN KEY (PEDIDOEMPRESAJUGUETE_JUGUETEID)
	REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_PEDIDOEMPRESAJUGUETE 
	UNIQUE (PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID , PEDIDOEMPRESAJUGUETE_JUGUETEID)
);
CREATE TABLE PEDIDOEMPRESAPARTICULAR(
	PEDIDOEMPRESAPARTICULAR_ID SMALLSERIAL,
	PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID SMALLSERIAL,
	PEDIODEMPRESAPARTICULAR_PARTICULAR_ID SMALLSERIAL,
	PEDIDOEMPRESAPARTICULAR_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PEDIDOEMPRESAPARTICULAR PRIMARY KEY (PEDIDOEMPRESAPARTICULAR_ID),
	CONSTRAINT FK_PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESAID 
	FOREIGN KEY (PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID)
	REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESAPARTICULAR_PARTICULARID
	FOREIGN KEY (PEDIODEMPRESAPARTICULAR_PARTICULAR_ID)
	REFERENCES PARTICULAR(PARTICULAR_ID),
	CONSTRAINT UQ_PEDIDOEMPRESAPARTICULAR 
	UNIQUE (PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID, PEDIODEMPRESAPARTICULAR_PARTICULAR_ID)
);
CREATE TABLE ALBARAN(
	ALBARAN_ID SMALLSERIAL,
	ALBARAN_PEDIDOID SMALLSERIAL,
	ALBARAN_FECHA DATE,
	CONSTRAINT PK_ALBARAN PRIMARY KEY (ALBARAN_ID),
	CONSTRAINT FK_ALBARANPEDIDOID 
	FOREIGN KEY (ALBARAN_PEDIDOID) 
	REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID)
);
CREATE TABLE ALBARANJUGUETE(
	ALBARANJUGUETE_ID SMALLSERIAL,
	ALBARANJUGUETE_ALBARAN_ID SMALLSERIAL,
	ALBARANJUGUETE_JUGUETE_ID SMALLSERIAL,
	ALBARANJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_ALBARANJUGUETE PRIMARY KEY (ALBARANJUGUETE_ID),
	CONSTRAINT FK_ALBARANJUGUETE_ALBARANID
	FOREIGN KEY (ALBARANJUGUETE_ALBARAN_ID)
	REFERENCES ALBARAN(ALBARAN_ID),
	CONSTRAINT FK_ALBARANJUGUETE_JUGUETEID
	FOREIGN KEY (ALBARANJUGUETE_JUGUETE_ID)
	REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_ALBARANJUGUETE 
	UNIQUE (ALBARANJUGUETE_ALBARAN_ID, ALBARANJUGUETE_JUGUETE_ID)
);
