CREATE TABLE JUGUETE (
	JUGUETE_ID SMALLSERIAL,
	JUGUETE_NOMBRE VARCHAR(30),
	JUGUETE_PRECIO NUMERIC(4, 2),
	JUGUETE_COSTE NUMERIC (4, 2),
	CONSTRAINT PK_JUGUETE PRIMARY KEY (JUGUETE_ID)
);
CREATE TABLE EMPRESA(
	EMPRESA_ID SMALLSERIAL,
	EMPRESA_NOMBRE VARCHAR(20),
	EMPRESA_CIF VARCHAR(20),
	EMPRESA_DIRECCIONPOSTAL VARCHAR(50),
	EMPRESA_DIRECCIONWEB VARCHAR(100),
	EMPRESA_TELEFONO VARCHAR(20),
	CONSTRAINT PK_EMPRESA PRIMARY KEY (EMPRESA_ID)
);
CREATE TABLE PARTICULAR(
	PARTICULAR_ID SMALLSERIAL,
	PARTICULAR_NOMBRE VARCHAR(20),
	PARTICULAR_APELLIDO VARCHAR(30),
	PARTICULAR_TELEFONO VARCHAR(20),
	PARTICULAR_DIRECCION VARCHAR(15),
	PARTICULAR_FIRMA VARCHAR(100),
	CONSTRAINT PK_PARTICULAR PRIMARY KEY (PARTICULAR_ID)
);
CREATE TABLE EMPRESAJUGUETE(
	EMPRESAJUGUETE_ID SMALLSERIAL,
	EMPRESAJUGUETE_EMPRESAID SMALLSERIAL NOT NULL,
	EMPRESAJUGUETE_JUGUETE SMALLSERIAL NOT NULL,
	EMPRESAJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_EMPRESAJUGUETE PRIMARY KEY (EMPRESAJUGUETE_ID),
	CONSTRAINT FK_EMPRESAJUGUETE_EMPRESAID FOREIGN KEY (EMPRESAJUGUETE_EMPRESAID) REFERENCES EMPRESA(EMPRESA_ID),
	CONSTRAINT FK_EMPRESAJUGUETE_JUGUETEID FOREIGN KEY (EMPRESAJUGUETE_JUGUETE) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_EMPRESAJUGUETE UNIQUE(EMPRESAJUGUETE_EMPRESAID, EMPRESAJUGUETE_JUGUETE)
);
CREATE TABLE PARTICULARJUGUETE(
	PARTICULARJUGUETE_ID SMALLSERIAL,
	PARTICULARJUGUETE_PARTICULARID SMALLSERIAL NOT NULL,
	PARTICULARJUGUETE_JUGUETEID SMALLSERIAL NOT NULL,
	PARTICULARJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PARTICULARJUGUETE PRIMARY KEY (PARTICULARJUGUETE_ID),
	CONSTRAINT FK_PARTICULARJUGUETE_PARTICULARID FOREIGN KEY (PARTICULARJUGUETE_PARTICULARID) REFERENCES PARTICULAR(PARTICULAR_ID),
	CONSTRAINT FK_PARTICULARJUGUETE_JUGUETEID FOREIGN KEY (PARTICULARJUGUETE_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_PARTICULARJUGUETE UNIQUE (
		PARTICULARJUGUETE_PARTICULARID,
		PARTICULARJUGUETE_JUGUETEID
	)
);
CREATE TABLE PEDIDOEMPRESA(
	PEDIDOEMPRESA_ID SMALLSERIAL,
	PEDIDOEMPRESA_EMPRESAID SMALLSERIAL NOT NULL,
	PEDIDOEMPRESA_FECHA DATE,
	PEDIDOEMPRESA_DIRECCIONENVIO VARCHAR(50),
	CONSTRAINT PK_PEDIDOEMPRESA PRIMARY KEY (PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESA_EMPRESAID FOREIGN KEY (PEDIDOEMPRESA_EMPRESAID) REFERENCES EMPRESA(EMPRESA_ID)
);
CREATE TABLE PEDIDOPARTICULAR (
	PEDIDOPARTICULAR_ID SMALLSERIAL,
	PEDIDOPARTICULAR_PARTICULARID SMALLSERIAL NOT NULL,
	PEDIDOPARTICULAR_FECHA DATE,
	CONSTRAINT PK_PEDIDOPARTICULAR PRIMARY KEY (PEDIDOPARTICULAR_ID),
	CONSTRAINT FK_PEDIDOPARTICULAR_PARTICULARID FOREIGN KEY (PEDIDOPARTICULAR_PARTICULARID) REFERENCES PARTICULAR(PARTICULAR_ID)
);
CREATE TABLE PEDIDOEMPRESAJUGUETE(
	PEDIDOEMPRESAJUGUETE_ID SMALLSERIAL,
	PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID SMALLSERIAL NOT NULL,
	PEDIDOEMPRESAJUGUETE_JUGUETEID SMALLSERIAL NOT NULL,
	PEDIDOEMPRESAJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PEDIDOEMPRESAJUGUETE PRIMARY KEY (PEDIDOEMPRESAJUGUETE_ID),
	CONSTRAINT FK_PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID FOREIGN KEY (PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID) REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESAJUGUETE_JUGUETEID FOREIGN KEY (PEDIDOEMPRESAJUGUETE_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_PEDIDOEMPRESAJUGUETE UNIQUE (
		PEDIDOEMPRESAJUGUETE_PEDIDOEMPRESAID,
		PEDIDOEMPRESAJUGUETE_JUGUETEID
	)
);
CREATE TABLE PEDIDOEMPRESAPARTICULAR(
	PEDIDOEMPRESAPARTICULAR_ID SMALLSERIAL,
	PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID SMALLSERIAL NOT NULL,
	PEDIODEMPRESAPARTICULAR_PARTICULAR_ID SMALLSERIAL NOT NULL,
	PEDIDOEMPRESAPARTICULAR_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_PEDIDOEMPRESAPARTICULAR PRIMARY KEY (PEDIDOEMPRESAPARTICULAR_ID),
	CONSTRAINT FK_PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESAID FOREIGN KEY (PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID) REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID),
	CONSTRAINT FK_PEDIDOEMPRESAPARTICULAR_PARTICULARID FOREIGN KEY (PEDIODEMPRESAPARTICULAR_PARTICULAR_ID) REFERENCES PARTICULAR(PARTICULAR_ID),
	CONSTRAINT UQ_PEDIDOEMPRESAPARTICULAR UNIQUE (
		PEDIDOEMPRESAPARTICULAR_PEDIDOEMPRESA_ID,
		PEDIODEMPRESAPARTICULAR_PARTICULAR_ID
	)
);
CREATE TABLE ALBARAN(
	ALBARAN_ID SMALLSERIAL,
	ALBARAN_PEDIDOID SMALLSERIAL,
	ALBARAN_FECHA DATE,
	CONSTRAINT PK_ALBARAN PRIMARY KEY (ALBARAN_ID),
	CONSTRAINT FK_ALBARANPEDIDOID FOREIGN KEY (ALBARAN_PEDIDOID) REFERENCES PEDIDOEMPRESA(PEDIDOEMPRESA_ID)
);
CREATE TABLE ALBARANJUGUETE(
	ALBARANJUGUETE_ID SMALLSERIAL,
	ALBARANJUGUETE_ALBARAN_ID SMALLSERIAL NOT NULL,
	ALBARANJUGUETE_JUGUETE_ID SMALLSERIAL NOT NULL,
	ALBARANJUGUETE_CANTIDAD NUMERIC(3),
	CONSTRAINT PK_ALBARANJUGUETE PRIMARY KEY (ALBARANJUGUETE_ID),
	CONSTRAINT FK_ALBARANJUGUETE_ALBARANID FOREIGN KEY (ALBARANJUGUETE_ALBARAN_ID) REFERENCES ALBARAN(ALBARAN_ID),
	CONSTRAINT FK_ALBARANJUGUETE_JUGUETEID FOREIGN KEY (ALBARANJUGUETE_JUGUETE_ID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT UQ_ALBARANJUGUETE UNIQUE (
		ALBARANJUGUETE_ALBARAN_ID,
		ALBARANJUGUETE_JUGUETE_ID
	)
);
CREATE TABLE CLIENTE (
	CLIENTE_ID SMALLSERIAL,
	CLIENTE_NOMBRE VARCHAR(20) NOT NULL,
	CLIENTE_APELLIDO VARCHAR(40) NOT NULL,
	CLIENTE_PASS VARCHAR(20) NOT NULL,
	CLIENTE_EMAIL VARCHAR(50) NOT NULL,
	CLIENTE_PHONE VARCHAR(12),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_ID)
);
CREATE TABLE DIRECCIONENVIO (
	DIRECCIONENVIO_ID SMALLSERIAL,
	DIRECCIONENVIO_CLIENTEID SMALLSERIAL NOT NULL,
	DIRECCIONENVIO_NOMBRE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_DIRECCIONEVIO PRIMARY KEY (DIRECCIONENVIO_ID)
	CONSTRAINT FK_DIRECCIONENVIO FOREIGN KEY (DIRECCIONENVIO_CLIENTEID) REFERENCES CLIENTE(CLIENTE_ID)
);
CREATE TABLE DIRECCIONFACTURACION(
	DIRECCIONFACTURACION_ID SMALLSERIAL,
	DIRECCIONENVIO_CLIENTEID SMALLSERIAL NOT NULL,
	DIRECCIONFACTURACION_NOMBRE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_DIRECCIONFACTURACION PRIMARY KEY (DIRECCIONFACTURACION_NOMBRE)
	CONSTRAINT FK_DIRECCIONFACTURACION FOREIGN KEY (DIRECCIONFACTURACION_CLIENTEID) REFERENCES CLIENTE(CLIENTE_ID)
);
CREATE TABLE PEDIDO_CLIENTE(
	PEDIDOCLIENTE_ID SMALLSERIAL,
	PEDIDOCLIENTE_CLIENTEID SMALLSERIAL NOT NULL,
	CONSTRAINT PK_PEDIDOCLIENTE PRIMARY KEY (PEDIDOCLIENTE_ID)
);
CREATE TABLE LINEAPEDIDO(
	LINEAPEDIDO_ID SMALLSERIAL,
	LINEAPEDIDO_JUGUETEID SMALLSERIAL,
	LINEAPEDIDO_PEDIDOID SMALLSERIAL,
	LINEAPEDIDO_CANTIDAD NUMERIC(3),
	LINEAPEDIDO_COSTE NUMERIC(5,2),
	CONSTRAINT PK_LINEAPEDIDO PRIMARY KEY (LINEAPEDIDO_ID),
	CONSTRAINT FK_LINEAPEDIDO_JUGUETEID FOREIGN KEY (LINEAPEDIDO_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT FK_LINEAPEDIDO_PEDIDOID FOREIGN KEY (LINEAPEDIDO_PEDIDOID) REFERENCES PEDIDO(PEDIDO_ID),
	CONSTRAINT UQ_LINEAPEDIDO UNIQUE (LINEAPEDIDO_JUGUETEID, LINEAPEDIDO_PEDIDOID)
);
CREATE TABLE CLIENTEFACTURA(
	CLIENTEFACTURA_ID SMALLSERIAL,
	CLIENTEFACTURA_DIRECCIONFACTURACIONID SMALLSERIAL,
	CLIENTEFACTURA_FECHA DATE,
	CLIENTEFACTURA_MPAGO NUMERIC (3),
	CONSTRAINT PK_CLIENTEFACTURA PRIMARY KEY (CLIENTEFACTURA_ID),
	CONSTRAINT FK_CLIENTEFACTURA FOREIGN KEY (CLIENTEFACTURA_DIRECCIONFACTURACIONID) REFERENCES DIRECCIONFACTURACION(DIRECCINFACTURACION_ID)
);
CREATE TABLE CLIENTELABARAN(
	CLIENTEALBARAN_ID SMALLSERIAL,
	CLIENTEALBARAN_DIRECCIONENVIO_ID SMALLSERIAL,
	CLIENTALBARAN_PEDIDOCLIENTEID SMALLSERIAL NOT NULL,
	CLIENTEALBARAN_CLIENTEFACTURAID SMALLSERIAL,
	CLIENTEALBARAN_ACEPTADO BOOLEAN,
	CLIENTEALBARAN_FECHA DATE,
	CONSTRAINT PK_CLIENTEALBARAN PRIMARY KEY (CLIENTEALBARAN_ID),
	CONSTRAINT FK_CLIENTALBARAN_PEDIDOCLIENTEID FOREIGN KEY (CLIENTALBARAN_PEDIDOCLIENTEID) REFERENCES PEDIDO_CLIENTE(PEDIDOCLIENTE_ID),
	CONSTRAINT FK_CLIENTEALBARAN_CLIENTEFACTURAID FOREIGN KEY (CLIENTEALBARAN_CLIENTEFACTURAID) REFERENCES CLIENTEFACTURA(CLIENTEFACTURA_ID)
);
CREATE TABLE LINEAALBARAN(
	LINEAALBARAN_ID SMALLSERIAL,
	LINEAALBARAN_JUGUETEID SMALLSERIAL,
	LINEAALBARAN_ALBARANID SMALLSERIAL,
	LINEAALBARAN_CANTIDAD NUMERIC(3),
	LINEAALBARAN_COSTE NUMERIC(5,2),
	CONSTRAINT PK_LINEAALBARAN PRIMARY KEY (LINEAALBARAN_ID),
	CONSTRAINT FK_LINEAALBARAN_JUGUETEID FOREIGN KEY (LINEAALBARAN_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT FK_LINEAALBARAN_ALBARANID FOREIGN KEY (LINEAALBARAN_ALBARANID) REFERENCES CLIENTEALBARAN(CLIENTEALBARAN_ID),
	CONSTRAINT UQ_LINEAALBARAN UNIQUE (LINEAALBARAN_JUGUETEID, LINEAALBARAN_ALBARANID)
);
CREATE TABLE TICKET(
	TICKET_ID SMALLSERIAL,
	TICKET_DEVOLUCION DATE,
	CONSTRAINT PK_TICKET PRIMARY KEY (TICKET_ID)
);
CREATE TABLE PAGOTARJETA(
	PAGOTARJETA_ID SMALLSERIAL,
	PAGOTARJETA_TICKETID SMALLSERIAL,
	PAGOTARJETA_TITULAR VARCHAR(20),
	PAGOTARJETA_NUMERO VARCHAR(30),
	CONSTRAINT PK_PAGOTARJETA PRIMARY KEY (PAGOTARJETA_ID),
	CONSTRAINT FK_PAGOTJARETA FOREIGN KEY (PAGOTARJETA_TICKETID) REFERENCES TICKET(TICKET_ID)
);
CREATE TABLE LINEATICKET(
	LINEATICKET_ID SMALLSERIAL,
	LINEATICKET_JUGUETEID SMALLSERIAL,
	LINEATICKET_TICKETID SMALLSERIAL,
	LINEATICKET_CANTIDAD NUMERIC(3),
	LINEATICKET_PRECIO NUMERIC(5, 2),
	CONSTRAINT PK_LINEATICKET PRIMARY KEY (LINEATICKET_ID),
	CONSTRAINT FK_LINEATICKET_JUGUETEID FOREIGN KEY (LINEATICKET_JUGUETEID) REFERENCES JUGUETE(JUGUETE_ID),
	CONSTRAINT FK_LINEATICKET_TICKETID FOREIGN KEY (LINEATICKET_TICKETID) REFERENCES TICKET(TICKET_ID),
	CONSTRAINT UQ_LINEATICKET UNIQUE (LINEATICKET_JUGUETEID, LINEATICKET_TICKETID)
);
