-- Insert 1
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa1', 'CIF1', 'Dirección1', 'www.empresa1.com', '123-456-789');

-- Insert 2
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa2', 'CIF2', 'Dirección2', 'www.empresa2.com', '987-654-321');

-- Insert 3
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa3', 'CIF3', 'Dirección3', 'www.empresa3.com', '555-123-777');

-- Insert 4
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa4', 'CIF4', 'Dirección4', 'www.empresa4.com', '111-222-333');

-- Insert 5
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa5', 'CIF5', 'Dirección5', 'www.empresa5.com', '999-888-777');

-- Insert 6
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa6', 'CIF6', 'Dirección6', 'www.empresa6.com', '444-555-666');

-- Insert 7
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa7', 'CIF7', 'Dirección7', 'www.empresa7.com', '777-888-999');

-- Insert 8
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa8', 'CIF8', 'Dirección8', 'www.empresa8.com', '222-111-333');

-- Insert 9
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa9', 'CIF9', 'Dirección9', 'www.empresa9.com', '666-555-444');

-- Insert 10
INSERT INTO EMPRESA (EMPRESA_NOMBRE, EMPRESA_CIF, EMPRESA_DIRECCIONPOSTAL, EMPRESA_DIRECCIONWEB, EMPRESA_TELEFONO)
VALUES ('Empresa10', 'CIF10', 'Dirección10', 'www.empresa10.com', '333-222-111');
