CREATE TABLE SP_USER (
	USER_ID SERIAL,
	USER_NICK VARCHAR,
	USER_DNI VARCHAR,
	USER_FNAME VARCHAR,
	USER_LNAME VARCHAR,
	USER_PHOTO VARCHAR,
	USER_EMAIL VARCHAR,
	USER_PASS VARCHAR,
	USER_PHONE NUMERIC,
	USER_JOINDATE DATE,
	CONSTRAINT PK_SP_USER PRIMARY KEY (USER_ID)
);
CREATE TABLE SP_PROYECT (
	PROYECT_ID SERIAL,
	PROYECT_NAME VARCHAR,
	PROYECT_DESC VARCHAR,
	ROYECT_PHOTO VARCHAR,
	PROYECT_DATE DATE,
	CONSTRAINT PK_PROYECT PRIMARY KEY (PROYECT_ID)
);
CREATE TABLE SP_USERPROYECT (
	USERPROYECT_ID SERIAL,
	USER_ID SERIAL,
	PROYECT_ID SERIAL,
	CONSTRAINT PK_USERPROYECT PRIMARY KEY (USERPROYECT_ID),
	CONSTRAINT FK_USERPROYECT_USER_ID FOREIGN KEY (USER_ID) REFERENCES SP_USER(USER_ID),
	CONSTRAINT FK_USERPROYECT_PROYECT_ID FOREIGN KEY (PROYECT_ID) REFERENCES SP_PROYECT(PROYECT_ID),
	CONSTRAINT UQ_UPSERPROYECT UNIQUE (USER_ID, PROYECT_ID)
);
CREATE TABLE SP_USERREQUEST(
	USERREQUEST_ID SERIAL,
	USER_ID SERIAL,
	PROYECT_ID SERIAL,
	CONSTRAINT PK_USERREQUEST PRIMARY KEY (USERREQUEST_ID),
	CONSTRAINT FK_USERREQUEST_USER_ID FOREIGN KEY (USER_ID) REFERENCES SP_USER(USER_ID),
	CONSTRAINT FK_USERREQUEST_PROYECT_ID FOREIGN KEY (PROYECT_ID) REFERENCES SP_PROYECT(PROYECT_ID),
	CONSTRAINT UQ_USERREQUEST UNIQUE (USER_ID, PROYECT_ID)
);
CREATE TABLE SP_EVENT (
	EVENT_ID SERIAL,
	PROYECT_ID SERIAL,
	EVENT_NAME VARCHAR,
	EVENT_DESC VARCHAR,
	CONSTRAINT PK_EVENT PRIMARY KEY (EVENT_ID),
	CONSTRAINT FK_EVENT FOREIGN KEY (PROYECT_ID) REFERENCES SP_PROYECT(PROYECT_ID)
);
CREATE TABLE SP_USEREVENT(
	USEREVENT_ID SERIAL,
	USEREVENT_USER_ID SERIAL,
	USEREVENT_PROYECT_ID SERIAL,
	USEREVENT_NAME VARCHAR,
	USEREVENT_DESC VARCHAR,
	CONSTRAINT PK_USEREVENT PRIMARY KEY (USEREVENT_ID),
	CONSTRAINT FK_USEREVENT_USER_ID FOREIGN KEY (USEREVENT_USER_ID) REFERENCES SP_USER(USER_ID),
	CONSTRAINT FK_USEREVENT_PROYECT_ID FOREIGN KEY (USEREVENT_PROYECT_ID) REFERENCES SP_PROYECT(PROYECT_ID),
	CONSTRAINT UQ_USEREVENT UNIQUE (USEREVENT_USER_ID, USEREVENT_PROYECT_ID)
	
);
