CREATE TABLE ORGANIZADOR(
    ORGANIZADOR_ID INT AUTO_INCREMENT,
    ORGANIZADOR_NOMBRE VARCHAR(255),
    ORGANIZADOR_TIPO VARCHAR(255),
    ORGANIZADOR_PAIS VARCHAR(255),
    ORGANIZADOR_EMAIL VARCHAR(255),
    ORGANIZADOR_TELEFONO VARCHAR(255),
    PRIMARY KEY (ORGANIZADOR_ID)
);
CREATE TABLE PROYECTO(
    PROYECTO_ID INT AUTO_INCREMENT,
    PROYECTO_ORGANIZADOR INT,
    PROYECTO_NOMBRE VARCHAR(255),
    PROYECTO_TIPO VARCHAR(255),
    PROYECTO_DESCRIPCION VARCHAR(255),
    PROYECTO_ESTADO VARCHAR(255),
    PROYECTO_EXTRA VARCHAR(255),
    PRIMARY KEY (PROYECTO_ID),
    FOREIGN KEY (PROYECTO_ORGANIZADOR) REFERENCES ORGANIZADOR(ORGANIZADOR_ID)
);
CREATE TABLE PERFIL(
    PERFIL_ID INT AUTO_INCREMENT,
    PERFIL_TITULO VARCHAR(255),
    PERFIL_DESCRIPCION VARCHAR(255),
    PRIMARY KEY (PERFIL_ID)
);
CREATE TABLE PROYECTOPERFIL(
    PROYECTOPERFIL_ID INT AUTO_INCREMENT,
    PROYECTOPERFIL_PROYECTO_ID INT,
    PROYECTOPERFIL_PERFIL_ID INT,
    PRIMARY KEY (PROYECTOPERFIL_ID),
    UNIQUE KEY UQ_PROYECTOPERFIL (
        PROYECTOPERFIL_PROYECTO_ID,
        PROYECTOPERFIL_PERFIL_ID
    ),
    FOREIGN KEY (PROYECTOPERFIL_PROYECTO_ID) REFERENCES PROYECTO(PROYECTO_ID),
    FOREIGN KEY (PROYECTOPERFIL_PERFIL_ID) REFERENCES PERFIL(PERFIL_ID)
);
CREATE TABLE ETIQUETA(
    ETIQUETA_ID INT AUTO_INCREMENT,
    ETIQUETA_DESCRIPCION VARCHAR(255),
    PRIMARY KEY (ETIQUETA_ID)
);
CREATE TABLE PERFILETIQUETA(
    PERFILETIQUETA_ID INT AUTO_INCREMENT,
    PERFILETIQUETA_PERFIL_ID INT,
    PERFILETIQUETA_ETIQUETA_ID INT,
    PRIMARY KEY (PERFILETIQUETA_ID),
    FOREIGN KEY (PERFILETIQUETA_PERFIL_ID) REFERENCES PERFIL(PERFIL_ID),
    FOREIGN KEY (PERFILETIQUETA_ETIQUETA_ID) REFERENCES ETIQUETA(ETIQUETA_ID),
    UNIQUE KEY UQ_PERFILETIQUETA (
        PERFILETIQUETA_PERFIL_ID,
        PERFILETIQUETA_ETIQUETA_ID
    )
);
CREATE TABLE COLABORADOR(
    COLABORADOR_ID INT AUTO_INCREMENT,
    COLABORADOR_CURRICULUM_ID INT,
    COLABORADOR_NOMBRE VARCHAR(255),
    COLABORADOR_APELLIDOS VARCHAR(255),
    COLABORADOR_EMAIL VARCHAR(255),
    COLABORADOR_PERFILIMG VARCHAR(255),
    COLABORADOR_CONTRASENA VARCHAR(255),
    COLABORADOR_PAIS VARCHAR(255),
    COLABORADOR_ESTADO VARCHAR(255),
    PRIMARY KEY (COLABORADOR_ID)
);
CREATE TABLE CURRICULUM(
    CURRICULUM_ID INT AUTO_INCREMENT,
    CURRICULUM_COLABORADOR_ID INT,
    CURRICULUM_DESCRIPCION VARCHAR(255),
    CURRICULUM_EXTRA VARCHAR(255),
    PRIMARY KEY (CURRICULUM_ID)
);
ALTER TABLE COLABORADOR
ADD FOREIGN KEY (COLABORADOR_CURRICULUM_ID) REFERENCES CURRICULUM(CURRICULUM_ID);
ALTER TABLE CURRICULUM
ADD FOREIGN KEY (CURRICULUM_COLABORADOR_ID) REFERENCES COLABORADOR(COLABORADOR_ID);
CREATE TABLE SKILL(
    SKILL_ID INT AUTO_INCREMENT,
    SKILL_TITULO VARCHAR(255),
    SKILL_ESTADO VARCHAR(255),
    PRIMARY KEY (SKILL_ID)
);
CREATE TABLE IDIOMA(
    IDIOMA_ID INT AUTO_INCREMENT,
    IDIOMA_TITULO VARCHAR(255),
    IDIOMA_ESTADO VARCHAR(255),
    PRIMARY KEY (IDIOMA_ID)
);
CREATE TABLE SKILLCV(
    SKILLCV_ID INT AUTO_INCREMENT,
    SKILLCV_SKILL_ID INT,
    SKILLCV_CURRICULUM_ID INT,
    SKILLCV_NIVEL VARCHAR(255),
    PRIMARY KEY (SKILLCV_ID),
    FOREIGN KEY (SKILLCV_SKILL_ID) REFERENCES SKILL(SKILL_ID),
    FOREIGN KEY (SKILLCV_CURRICULUM_ID) REFERENCES CURRICULUM(CURRICULUM_ID),
    UNIQUE KEY UQ_SKILLCV (SKILLCV_SKILL_ID, SKILLCV_CURRICULUM_ID)
);
CREATE TABLE IDIOMACV(
    IDIOMACV_ID INT AUTO_INCREMENT,
    IDIOMACV_IDIOMA_ID INT,
    IDIOMACV_CURRICULUM_ID INT,
    IDIOMACV_NIVEL VARCHAR(255),
    PRIMARY KEY (IDIOMACV_ID),
    FOREIGN KEY (IDIOMACV_IDIOMA_ID) REFERENCES IDIOMA(IDIOMA_ID),
    FOREIGN KEY (IDIOMACV_CURRICULUM_ID) REFERENCES CURRICULUM(CURRICULUM_ID),
    UNIQUE KEY UQ_IDIOMACV (IDIOMACV_IDIOMA_ID, IDIOMACV_CURRICULUM_ID)
);
CREATE TABLE SOLICITUD(
    SOLICITUD_ID INT AUTO_INCREMENT,
    SOLICITUD_PROYECTO_ID INT,
    SOLICITUD_COLABORADOR_ID INT,
    PRIMARY KEY (SOLICITUD_ID),
    FOREIGN KEY (SOLICITUD_PROYECTO_ID) REFERENCES PROYECTO(PROYECTO_ID),
    FOREIGN KEY (SOLICITUD_COLABORADOR_ID) REFERENCES COLABORADOR(COLABORADOR_ID),
    UNIQUE KEY UQ_SOLICITUD (SOLICITUD_PROYECTO_ID, SOLICITUD_COLABORADOR_ID)
);
CREATE TABLE COLABORADORPROYECTO(
    COLABORADORPROYECTO_ID INT AUTO_INCREMENT,
    COLABORADORPROYECTO_COLABORADOR_ID INT,
    COLABORADORPROYECTO_PROYECTO_ID INT,
    CONSTRAINT PK_COLABORADORPROYECTO PRIMARY KEY (COLABORADORPROYECTO_ID),
    CONSTRAINT FK_COLABORADORPROYECTO_COLABORADOR_ID FOREIGN KEY (COLABORADORPROYECTO_COLABORADOR_ID) REFERENCES COLABORADOR(COLABORADOR_ID),
    CONSTRAINT FK_COLABORADORPROYECTO FOREIGN KEY (COLABORADORPROYECTO_PROYECTO_ID) REFERENCES PROYECTO(PROYECTO_ID),
    CONSTRAINT UQ_COLABORADORPROYECTO UNIQUE (
        COLABORADORPROYECTO_COLABORADOR_ID,
        COLABORADORPROYECTO_PROYECTO_ID
    )
);
