DECLARE v_dept99 NUMBER(2) BEGIN
SELECT COUNT(*) INTO v_dept99
FROM DEPART
WHERE DEPT_NO = 99;
IF(v_dept99 = 0) THEN
INSERT INTO DEPART
VALUES (99, 'Temporal', 'Temporal');
END IF;
UPDATE EMPLE
SET dept_no = 99
WHERE dept_no = 10;
DELETE FROM DEPART
WHERE dept_no = 10;
END;
/
